### ISSUE TITLE
ImportError: No module named _kmeans

### ISSUE THREAD

**Issue by xternalz** [thomas-bottesch/fcl#14]
I got this when I tried to import kmeans

```
Traceback (most recent call last):                                                                                   
  File "<stdin>", line 1, in <module>                                                                                
  File "fcl/kmeans/__init__.py", line 1, in <module>                                                                 
    from .kmeans import KMeans, from_pickle, StopException, print_algorithm_info, print_initialization_info          
  File "fcl/kmeans/kmeans.py", line 2, in <module>                                                                   
    from ._kmeans import KMEANS_ALGO_INFO, KMEANS_INIT_INFO                                                          
ImportError: No module named _kmeans
```

**Comment by thomas-bottesch** [comment]
Hi xternalz,

our continous integration environment performs the following steps in order to work:
from the main folder where the Makefile is located:

 sudo apt-get install -qq -y libpng-dev libfreetype6-dev libxft-dev   # needed to get matplotlib to work
 pip install --upgrade pip
 pip install -r python/requirements.txt
 pip install -r python/requirements_examples.txt

Then to install fcl in your python environment:

cd python
python setup.py install

Now you should **_not_** try to do this directly:

`import fcl`

because you are still in this folder:

```
build
fcl
fcl.egg-info
requirements_examples.txt
requirements.txt
setup.py
```

If you do an import here you will import the fcl package from the current folder which is the wrong one.
You need to change your current working directory to a different folder. By doing e.g.
```
cd ..
```

Then you can import fcl.

**Comment by thomas-bottesch** [comment]
The library is now installable via:

`pip install fcl`

without downloading downloading the code from github
